### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by navinprasadk** [HandlebarLabs/currency-converter-starter#11]
After including **LastConverted**  component in **Home** screen, I'm getting this error **Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports**
![rn-error](https://user-images.githubusercontent.com/24914744/37250773-a1692fec-2529-11e8-88e5-f831a57277b5.png)

**Comment by navinprasadk** [comment]
This is the Home screen code

`import React, { Component } from 'react';
import { StatusBar } from 'react-native';
import { Container } from '../components/Container';
import { Logo } from '../components/Logo';
import { InputWithButton } from '../components/TextInput';
import { ClearButton } from '../components/Button';
import { LastConverted } from '../components/Text';

const TEMP_BASE_CURRENCY = 'USD';
const TEMP_QUOTE_CURRENCY = 'INR';
const TEMP_BASE_PRICE = '100';
const TEMP_QUOTE_PRICE = '79.74';
const TEMP_CONVERSION_RATE = 0.79;
const TEMP_LAST_CONVERTED = new Date();

class Home extends Component {
 
  handlePressBaseCurrency = () => {
    console.log('====================================');
    console.log('handle base currency');
    console.log('====================================');
  };
  handlePressQuoteCurrency = () => {
    console.log('====================================');
    console.log('handle quote currency');
    console.log('====================================');
  };
  handleTextChange = (text) => {
    console.log('====================================');
    console.log('change text', text);
    console.log('====================================');
  };
  handleSwapCurrency = () => {
    console.log('handle swap currency');
  };

  render() {
    return (
      <Container>
        <StatusBar />
        <Logo />
        <InputWithButton
          buttonText={TEMP_BASE_CURRENCY}
          onPress={this.handlePressBaseCurrency}
          defaultValue={TEMP_BASE_PRICE}
          keyboardType="numeric"
          onChange={this.handleTextChange}
        />
        <InputWithButton
          buttonText={TEMP_QUOTE_CURRENCY}
          onPress={this.handlePressQuoteCurrency}
          editable={false}
          value={TEMP_QUOTE_PRICE}
        />

        <LastConverted
          date={TEMP_LAST_CONVERTED}
          base={TEMP_BASE_CURRENCY}
          quote={TEMP_QUOTE_CURRENCY}
          conversionRate={TEMP_CONVERSION_RATE}
        />
        <ClearButton onPress={this.handleSwapCurrency} text="Reverse Currencies" />
      </Container>
    );
  }
}

export default Home;
`

**Comment by spencercarli** [comment]
I need two things to help

1. What's your `LastConverted` code look like? 
2. What's your import logic look like in `Home`?

**Comment by navinprasadk** [comment]
I am sharing the GitHub link [here](https://github.com/navinprasadk/Currency-Converter-Mobile-App/tree/Header)

**Comment by spencercarli** [comment]
I believe your issue is in [`Text/index.js`](https://github.com/navinprasadk/Currency-Converter-Mobile-App/blob/Header/app/components/Text/index.js#L4) where you have

`export default { LastConverted, styles };`

it should be 

`export { LastConverted, styles };` (notice the lack of `default`).

That should work!

**Comment by navinprasadk** [comment]
Hey @spencercarli, thanks for your help! I didn't notice that one

**Comment by cesc1989** [comment]
hey @spencercarli I've got this same issue but mine indicates something different:

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `InputWithButton`.
```

Hope, you can check the actual state of my components in my repo: https://github.com/cesc1989/currency-converter I am clueless about this.

They're similar (or at least what I understand) to yours.

**Comment by spencercarli** [comment]
@cesc1989 can you open up a new issue?

**Comment by cesc1989** [comment]
@spencercarli [done](https://github.com/HandlebarLabs/currency-converter-starter/issues/15). Thanks for your help!
