### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string  error

### ISSUE THREAD

**Issue by orensaldanha** [HandlebarLabs/currency-converter-starter#13]
![d](https://user-images.githubusercontent.com/36854536/37473635-93cd1e16-2894-11e8-9784-17bf3504de09.PNG)

I'm in module 3 creating Home Container

**Comment by spencercarli** [comment]
Please look at the discussion in #11 to see if your issue is similar.

**Comment by domain90** [comment]
Hi, I have the same issue. I'm in module 3 Button. I checked my exports and they are correct.

Update: Solved it 👍
