### ISSUE TITLE
Where is nav.js file from the lecture

### ISSUE THREAD

**Issue by rendomnet** [HandlebarLabs/currency-converter-starter#14]
You created nav.js in the reducers folder.
https://learn.handlebarlabs.com/courses/175915/lectures/2830993

**Comment by spencercarli** [comment]
Unfortunately that lesson doesn't have any code to go with it. It was just a bit of a tangent in the course that isn't necessary for any future code.

**Comment by rendomnet** [comment]
But it was most important part for me. How to connect react navigation to redux.
Can you show the nav.js and routes.js source of this step please?

**Comment by rendomnet** [comment]
Okay I resolved it myself. Thnx anyway.
