### ISSUE TITLE
invariant violation: React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by kayafatih-net** [HandlebarLabs/currency-converter-starter#21]
where am i doing wrong.  I did copy and paste

**Comment by kayafatih-net** [comment]
this error is located at in AlertProvider (at index.js:22)

**Comment by spencercarli** [comment]
This isn't happening with the example code provided so I'm going to close this unless you can show me how to reproduce the error.

I have a feeling you wrote something differently though - make sure you're only passing one child to the `AlertProvider` component, like so:

```javascript
export default () => (
  <Provider store={store}>
    <AlertProvider>
      <Navigator onNavigationStateChange={null} />
    </AlertProvider>
  </Provider>
);
```
