### ISSUE TITLE
Phone stuck saying 'Open up App.js to start working on your app'

### ISSUE THREAD

**Issue by julielaursen** [HandlebarLabs/currency-converter-starter#30]
Hi, is there the paid resource that was discussed in the video and if so, where is it? Link? Is there a slack?

Additionally, I have gotten through the Home Screen: Container module and even set the background of my app to blue etc. However, on my iphone 7 that is on the same network as my laptop, the background just says 'Open up App.js to start working on your app'

I have App.js open in visual studio code and I've been able to successfully scan the QR code on my phone. What am I missing? I thought I wouldn't need a simulator to run this. 

I rewatched the first few modules a couple times to see what I missed, but I still have no idea

**Comment by spencercarli** [comment]
The course is linked in the Readme: https://github.com/HandlebarLabs/currency-converter-starter#free-react-native-course. 

The slack channel has been rolled into a different product (reactnativeschool.com).

Sounds like it's not picking up updates. In the Expo app, shake your device and a menu should pop up. You'll want to enable live reload.
