### ISSUE TITLE
[question] calling alert and alertType outside the component

### ISSUE THREAD

**Issue by damathryx** [HandlebarLabs/currency-converter-starter#4]
How do I implement triggering dropdownalert outside a component aside from callback? say inside a watcher function?

**Comment by spencercarli** [comment]
You'll need access to React context OR pass a [reference to the alert component](https://github.com/HandlebarLabs/currency-converter-starter/blob/module-7-lesson-4-upload/app/components/Alert/AlertProvider.js#L29) to wherever you need to use it.

**Comment by damathryx** [comment]
@spencercarli yes this is my question. how do i pass the reference outside the component?

**Comment by spencercarli** [comment]
I'm not sure how you're doing things but say you've got a function that, when something happens, should trigger the alert you can pass it as an argument.

```javascript
const doTheAlert = (alertWithType) => {
  alertWithType('error', 'Error');
}

class Home extends Component {
  componentWillReceiveProps(nextProps) {
    if (nextProps.currencyError && !this.props.currencyError) {
      doTheAlert(this.props.alertWithType);
    }
  }
}
```
